# Generated by Django 3.0.8 on 2020-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField(default='~/')),
                ('active', models.BooleanField(default='True')),
            ],
        ),
    ]
