# Generated by Django 3.0.8 on 2020-07-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_filelocations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filelocations',
            table='FILE_LOCATIONS',
        ),
        migrations.AlterModelTable(
            name='photos',
            table='PHOTOS',
        ),
    ]
